openapi: 3.0.1
info:
  title: Todo-Listen-Verwaltung
  version: 1.0.0
  description: Eine REST-API zur Verwaltung von Todo-Listen und deren Einträgen.
  contact:
    email: f.kroeger@ambition-performance.de
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html

servers:
  - url: http://127.0.0.1:5000/

tags:
  - name: Listenverwaltung
    description: Endpunkte zur Verwaltung von Todo-Listen und deren Einträgen

paths:

  /todo-lists:
    get:
      tags: [Listenverwaltung]
      summary: Alle Listen anzeigen
      operationId: getAllLists
      responses:
        200:
          description: Liste aller Todo-Listen
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TodoList'
        500:
          description: Interner Serverfehler

  /todo-list:
    post:
      tags:
        - Listenverwaltung
      summary: Eine neue ToDo-Liste erstellen
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TodoList'
      responses:
        '200':
          description: Liste wurde erstellt
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TodoList'
        '400':
          description: Fehlerhafte Anfrage


  /todo-list/{list_id}:
    get:
      tags: [Listenverwaltung]
      summary: Eine Liste anzeigen
      operationId: getListById
      parameters:
        - name: list_id
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: Liste erfolgreich gefunden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TodoList'
        404:
          description: Liste nicht gefunden
        500:
          description: Interner Serverfehler

    delete:
      tags: [Listenverwaltung]
      summary: Liste löschen
      operationId: deleteList
      parameters:
        - name: list_id
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: Liste erfolgreich gelöscht
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
                    example: success
        404:
          description: Liste nicht gefunden
        500:
          description: Interner Serverfehler

  /todo-list/{list_id}/entries:
    get:
      tags: [Listenverwaltung]
      summary: Einträge einer Liste anzeigen
      operationId: getListEntries
      parameters:
        - name: list_id
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: Liste der Einträge
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TodoEntry'
        404:
          description: Liste nicht gefunden
        500:
          description: Interner Serverfehler

    post:
      tags: [Listenverwaltung]
      summary: Eintrag zu einer Liste hinzufügen
      operationId: addEntryToList
      parameters:
        - name: list_id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TodoEntry'
      responses:
        200:
          description: Eintrag erfolgreich hinzugefügt
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TodoEntry'
        400:
          description: Ungültiger Request
        404:
          description: Liste nicht gefunden
        500:
          description: Interner Serverfehler

  /todo-list/{list_id}/entry/{entry_id}:
    put:
      tags: [Listenverwaltung]
      summary: Eintrag aktualisieren
      operationId: updateEntry
      parameters:
        - name: list_id
          in: path
          required: true
          schema:
            type: string
        - name: entry_id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TodoEntry'
      responses:
        200:
          description: Eintrag erfolgreich aktualisiert
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TodoEntry'
        400:
          description: Ungültiger Request
        404:
          description: Eintrag oder Liste nicht gefunden
        500:
          description: Interner Serverfehler

    delete:
      tags: [Listenverwaltung]
      summary: Eintrag löschen
      operationId: deleteEntry
      parameters:
        - name: list_id
          in: path
          required: true
          schema:
            type: string
        - name: entry_id
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: Eintrag erfolgreich gelöscht
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
                    example: success
        404:
          description: Eintrag oder Liste nicht gefunden
        500:
          description: Interner Serverfehler

components:
  schemas:
    TodoList:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
    TodoEntry:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        description:
          type: string
        user_id:
          type: string
          format: uuid
        list_id:
          type: string
          format: uuid
